name: verify

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - '11'
          - '12'
          - '13'

    name: Verify on node ${{ matrix.node }}

    steps:
    - uses: actions/checkout@v1

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Restore yarn cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install npm modules
      run:
        yarn install

    - name: Verify app
      run:
        yarn lint

    - name: Build app
      run:
        yarn generate
